### ISSUE TITLE
is this missing something ?

### ISSUE THREAD

**Issue by captkhair** [Nebur96/MeteoClock#1]
i really like the project and i do have the ESP8266 ( NodeMCU ) and the TFT ili9341 2.2" .. i did find the 3D print file for the case but no code ? any help

**Comment by Nebur96** [comment]
Hi @captkhair, inside the folder [Meteoclock](https://github.com/Nebur96/MeteoClock/tree/master/Meteoclock) you have the code to set up this project. I have been using PlatformIO to program so you will no found the usual .ino file.

**Comment by captkhair** [comment]
thank you .. seems like i have to learn more about using the software 
the file you mean is example.ino ?

**Comment by Nebur96** [comment]
I'm assuming you use ArduinoIDE and with that IDE there is a main file for it to open the project that has the extension .ino and should have the same name of the workspace it is. The other files that have the extension .cpp will work as libs for the main project. With PlatformIO there is no .ino file and the main file will be the [main.cpp](https://github.com/Nebur96/MeteoClock/blob/master/Meteoclock/src/main.cpp) and all the other .cpp files will work as libs as in ArduinoIDE.
